
package com.thomsonreuters.ce.vtclient.history.jdk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HistoryOrderServiceService", targetNamespace = "http://webservice.vesseltracker.com/", wsdlLocation = "file:/D:/mywork/development/javaworkspace/VTWS/wsdl/HistoryOrderService.xml")
public class HistoryOrderServiceService
    extends Service
{

    private final static URL HISTORYORDERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTORYORDERSERVICESERVICE_EXCEPTION;
    private final static QName HISTORYORDERSERVICESERVICE_QNAME = new QName("http://webservice.vesseltracker.com/", "HistoryOrderServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/mywork/development/javaworkspace/VTWS/wsdl/HistoryOrderService.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTORYORDERSERVICESERVICE_WSDL_LOCATION = url;
        HISTORYORDERSERVICESERVICE_EXCEPTION = e;
    }

    public HistoryOrderServiceService() {
        super(__getWsdlLocation(), HISTORYORDERSERVICESERVICE_QNAME);
    }

    public HistoryOrderServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTORYORDERSERVICESERVICE_QNAME, features);
    }

    public HistoryOrderServiceService(URL wsdlLocation) {
        super(wsdlLocation, HISTORYORDERSERVICESERVICE_QNAME);
    }

    public HistoryOrderServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTORYORDERSERVICESERVICE_QNAME, features);
    }

    public HistoryOrderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoryOrderServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistoryOrderService
     */
    @WebEndpoint(name = "HistoryOrderServicePort")
    public HistoryOrderService getHistoryOrderServicePort() {
        return super.getPort(new QName("http://webservice.vesseltracker.com/", "HistoryOrderServicePort"), HistoryOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistoryOrderService
     */
    @WebEndpoint(name = "HistoryOrderServicePort")
    public HistoryOrderService getHistoryOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.vesseltracker.com/", "HistoryOrderServicePort"), HistoryOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTORYORDERSERVICESERVICE_EXCEPTION!= null) {
            throw HISTORYORDERSERVICESERVICE_EXCEPTION;
        }
        return HISTORYORDERSERVICESERVICE_WSDL_LOCATION;
    }

}
